version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8083:8083"
    networks:
      - springapimysql-net
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/Audit2?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Audit2
    command: ['--default-authentication-plugin=mysql_native_password']  # Add this line
    volumes:
      - db:/var/lib/mysql
    networks:
      - springapimysql-net

volumes:
  db:
    driver: local

networks:
  springapimysql-net:
